### ISSUE TITLE
log_parser plugin losing syslog

### ISSUE THREAD

**Issue by ppp0** [cargomedia/bipbip#105] opened 2015-02-11 17:00 UTC
Lots of errors in the log. `Bad file descriptor`

- db5: since Feb 5th 6:26
- stream2: Feb 9th 6:25
- db4: since Feb 9th 6:27
- db3: since Feb 9th 6:27
etc

Restarting bipbip everywhere...

**Comment by njam** [comment] 2015-02-16 13:23
In general the plugin detects the log rotation properly and reopens the file handle:
```
W, [2015-02-14T06:25:05.254000 #36314]  WARN -- log-parser db5.example.com::logparser-syslog::_var_log_syslog: File event `move_self` detected, resetting notifier
```

I can reproduce this locally, as well as see the log entries of it happening on production (daily).

Here's a part from the log where it didn't work (Feb 9th):
```
W, [2015-02-09T06:25:03.619617 #11854]  WARN -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: File event `move_self` detected, resetting notifier
E, [2015-02-09T06:27:32.412077 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
E, [2015-02-09T06:27:37.435994 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
E, [2015-02-09T06:27:47.484005 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
E, [2015-02-09T06:28:02.555993 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
E, [2015-02-09T06:28:22.656001 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
E, [2015-02-09T06:28:47.756022 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
E, [2015-02-09T06:29:17.855994 #11854] ERROR -- log-parser db3.example.com::logparser-syslog::_var_log_syslog: Bad file descriptor
```

...it looks like the `move_self` event was properly detected, and then 2.5 mins later the "Bad file descriptor" started.

I would suggest to add more verbose logging to find out where it fails exactly:
 https://github.com/cargomedia/bipbip/pull/106

**Comment by njam** [comment] 2015-02-26 15:13
Got it:
```
E, [2015-02-26T06:27:26.010648 #21064] ERROR -- log-parser ci3.cargomedia.ch::logparser-syslog::_var_log_syslog: Bad file descriptor
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/plugin/log_parser.rb:14:in `select'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/plugin/log_parser.rb:14:in `monitor'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/plugin.rb:33:in `block in run'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/plugin.rb:24:in `fork'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/plugin.rb:24:in `run'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/agent.rb:41:in `block in run'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/agent.rb:39:in `each'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/lib/bipbip/agent.rb:39:in `run'
 /var/lib/gems/1.9.1/gems/bipbip-0.5.20/bin/bipbip:43:in `<top (required)>'
 /usr/local/bin/bipbip:23:in `load'
 /usr/local/bin/bipbip:23:in `<main>'
```

**Comment by njam** [comment] 2015-02-26 18:00
Possibly related: http://compgroups.net/comp.lang.ruby/xrefresh-server-rb-inotify-and-ioselect/777709
(allthough I couldn't reproduce this exact behaviour)

**Comment by njam** [comment] 2015-02-27 18:09
It seems creating the `IO` object for the inotify notifier fails.
I can reproduce this and submitted a workaround here: https://github.com/nex3/rb-inotify/pull/43

**Comment by njam** [comment] 2015-03-03 14:44
Released GC run on inotify resetting on 2015-03-03

**Comment by njam** [comment] 2015-03-05 11:51
Didn't help...
Will look into other workarounds.

```
grep -m1 'Bad file descriptor' /var/log/bipbip/bipbip.log*
```

**Comment by njam** [comment] 2015-03-05 12:57
Released "resetting of inotify IO on EBADF" on: 2015-03-05

**Comment by njam** [comment] 2015-03-09 08:21
Released "Expect closing of notifier to fail" on: 2015-03-09

**Comment by njam** [comment] 2015-03-11 15:43
No occurences yet...
```
grep -m1 'EBADF' /var/log/bipbip/bipbip.log*
grep -m1 'Cannot close notifier' /var/log/bipbip/bipbip.log*
```

**Comment by njam** [comment] 2015-03-12 08:14
Ok we had "EBADF" occurences on a few servers.
Everything works as expected: EBADF is detected, notifier is reset, closing fails, notifier is recreated and logging properly.

Example excerpt:
```
W, [2015-03-12T06:25:10.113816 #30211]  WARN -- log-parser rep1-db4.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: File event `move_self` detected, resetting notifier
W, [2015-03-12T06:27:05.538317 #30211]  WARN -- log-parser rep1-db4.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: Selecting from inotify IO gives EBADF, resetting notifier
W, [2015-03-12T06:27:05.538518 #30211]  WARN -- log-parser rep1-db4.mongodb.fuckbook.com::logparser-syslog::_var_log_syslog: Cannot close notifier: `Bad file descriptor - Failed to properly close inotify socket: invalid or closed file descriptior`
```

**Closed** 2015-03-12 08:14 UTC
Labels: bug, in progress
